server:
  port: 9999


spring:
  datasource:
    username: root
    password: chenyin123
    url: jdbc:mysql:///xdb


  redis:
    port: 6379
    host: localhost

#logging:
#  level:
#  com.project: debug
